@startuml
title 对接模式一：问诊、购药、履约全部通过荷叶健康平台
autonumber
participant "渠道方" as channel
participant "开放平台" as openApi
participant "荷叶健康" as heye



====
alt 渠道方主动查询问诊信息
heye -> openApi : 问诊结束，回传问诊id
activate openApi #lightBlue
    openApi -> channel : 回传问诊id
    activate channel #lightGreen
        channel -> openApi: 根据问诊 id 查询问诊详情
end
====
alt 渠道方主动查询运单信息
channel -> openApi: 根据订单号查询运单信息
openApi -> heye : 根据订单号查询运单信息
activate heye #red
    heye -> openApi: 返回运单信息
deactivate heye
openApi -> channel: 返回运单信息
deactivate openApi
deactivate channel
end

alt 荷叶健康推送运单信息
heye -> openApi: 运单状态发生改变，回传物流信息
activate heye #red
activate openApi #lightBlue
    openApi -> channel: 运单状态发生改变，回传物流信息
deactivate openApi


end
@enduml