@startuml
autonumber

participant "汇仁医药" as  huiren
participant "荷叶健康" as heye
alt 同步库存
    huiren -> heye : 汇仁医药同步库存到荷叶健康
end

alt 下单交互
    huiren -> heye : 汇仁医药在荷叶将康平台下单
    activate huiren
    activate heye
        heye -> heye : 生成荷叶订单号，记录支付信息
        heye -> huiren : 荷叶健康将订单号、订单状态回传汇仁医药
        huiren -> heye : 根据订单号查询订单详情
        heye -> huiren : 返回订单信息
     deactivate heye
     deactivate huiren
end

alt 汇仁医药物流推送 : 正常发货
    huiren -> heye : 汇仁医药推送运单号，订单号给荷叶
    activate heye
        heye -> heye : 记录运单号，修改订单状态
    destroy heye
else 汇仁医药物流推送 : 发货失败
    huiren -> heye : 汇仁医药发送订单号, 以及发货失败原因
    activate heye
        heye -> heye : 记录订单号以及发货失败原因
    destroy heye
end

@enduml